apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: mydep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: mohamedosama45/cicdproject:latest
        name: cicdproject
        ports:
        - containerPort: 80
