vpc_name             = "my-vpc"
cidr_block           = "10.0.0.0/16"
subnet_cidr          = "10.0.1.0/24"
subnet_name          = "my-public-subnet"
igw_name             = "my-igw"
route_table_name     = "my-route-table"
ami_id               = "ami-084568db4383264d4"
instance_type        = "t2.large"
